import { ServicePrerequisite } from '../models/service-prerequisite.model'
export const RegistrationPreRequiste: ServicePrerequisite[] = [
    {
        ServicePrerequisiteId: 1,
        DocumentId: 1,
        IsDocument: 1,
        IsActive: true,
        ServiceId: 1,
        Description: "Where Application Is Submitted By Agent",
        BusinessType: 1,
        DescriptionEnglish: 'Copy Of Commercial Registration(If You Are Existing Customer)',
        ServiceNameEnglish: 'Copy Of Commercial Registration(If You Are Existing Customer)',
        upload: true,
        URL: 'string',
    },
    {
        ServicePrerequisiteId: 1,
        DocumentId: 2,
        IsDocument: 2,
        IsActive: true,
        ServiceId: 2,
        Description: "Application For Business License Duly Signed By Investor, ",
        BusinessType: 2,
        DescriptionEnglish: 'Application For Business License Duly Signed By Investor, ',
        ServiceNameEnglish: 'Application For Business License Duly Signed By Investor, ',
        upload: true,
        URL: 'string',
    },
    {
        ServicePrerequisiteId: 1,
        DocumentId: 3,
        IsDocument: 3,
        IsActive: true,
        ServiceId: 3,
        Description: "Where Application Is Submitted By Agent",
        BusinessType: 3,
        DescriptionEnglish: 'Where Application Is Submitted By Agent',
        ServiceNameEnglish: 'Where Application Is Submitted By Agent',
        upload: true,
        URL: 'string',
    },
    {
        ServicePrerequisiteId: 1,
        DocumentId: 4,
        IsDocument: 4,
        IsActive: true,
        ServiceId: 4,
        Description: "Where Application Is Submitted By Agent",
        BusinessType: 4,
        DescriptionEnglish: 'Copy Of Renewed Residence Permit Or An ID Card',
        ServiceNameEnglish: 'Copy Of Renewed Residence Permit Or An ID Card',
        upload: true,
        URL: 'string',
    },
    {
        ServicePrerequisiteId: 1,
        DocumentId: 5,
        IsDocument: 5,
        IsActive: true,
        ServiceId: 5,
        Description: "Four ¾-Inches Size Photographs Taken Within The Last Six Months",
        BusinessType: 5,
        DescriptionEnglish: 'Four ¾-Inches Size Photographs Taken Within The Last Six Months',
        ServiceNameEnglish: 'Four ¾-Inches Size Photographs Taken Within The Last Six Months',
        upload: true,
        URL: 'string',
    },


]